name: CyberClinic Standalone Application

services:

  # Windows builder can only be run on Windows host or VM
  build_windows:
    #image: python:3.14
    platform: "windows/amd64"
    volumes:
      - ./src:/shared
      - ./dist:/dist
    build:
      target: win_builder
    #command: "pyinstaller --distpath C:\\dist\\windows -n CyberClinic --noconfirm client_application.py"
    #command: ["cmd"]
  
  build_linux:
    image: python:3.14
    platform: "linux/amd64"
    volumes:
      - ./src:/src/
      - ./dist:/dist
    build:
      target: linux_builder
    #command: "python -m  PyInstaller --distpath /dist/linux -n CyberClinic --noconfirm client_application.py"
    #command: ["sleep", "infinity"]
    
  build_macos:
    image: dockurr/macos
    environment:
      VERSION: "11"
    volumes:
      - ./src:/src
      - ./dist:/dist
    build:
      args:
        - VERSION=${VERSION}
      target: mac_builder