name: CyberClinic Standalone Application

services:
  
  build_linux:
    image: python:3.14
    volumes:
      - ./src:/src/
      - ./dist:/dist
    build:
      target: linux_builder
    
  build_macos:
    image: dockurr/macos
    environment:
      VERSION: "11"
    volumes:
      - ./src:/src
      - ./dist:/dist
    build:
      args:
        - VERSION=${VERSION}
      target: mac_builder