#!/bin/bash
# Server - Generate authentication tunnel cert
openssl req -x509 -days 365 -newkey rsa:2048 -keyout ${AUTH_KEY} -out ${AUTH_CRT} -passout env:AUTH_PASS -config ${SERVER_CNF}
# Server - Generate authenticated tunnel cert
openssl req -x509 -days 365 -newkey rsa:2048 -keyout ${AUTHED_KEY} -out ${AUTHED_CRT} -passout env:AUTHED_PASS -config ${SERVER_CNF}
