FROM node:24-alpine

RUN apk update && apk add --no-cache \
    curl \
    openssl \
    && rm -rf /var/cache/apk/*

WORKDIR /cyberclinic

COPY cyberclinicreact/ .

RUN npm install --force

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost:3000/ || exit 1

#done by Austin Finch