name: CyberClinic Web Portal

services:

  frontend:
    container_name: cyberclinic-frontend
    environment:
      - REACT_APP_FRONTEND_SERVER=${FRONTEND_SERVER}
      - REACT_APP_FRONTEND_PORT=${FRONTEND_PORT}
      - REACT_APP_BACKEND_SERVER=http://${HOST}:${BACKEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      #backend:
      #  condition: service_healthy
      # Run with development backend
      backend-dev:
        condition: service_healthy
    networks:
      - frontend
    command: npm start

  backend:
    container_name: cyberclinic-backend
    build:
      context: backend
      target: builder
      args:
        - BACKEND_SERVER=${BACKEND_SERVER-backend}
        - BACKEND_PORT=${BACKEND_PORT:-5000}
        - AUTHED_CRT=${AUTHED_CRT}
    volumes:
      - ./backend:/src
    environment:
      - SCAN_DIR=${SCAN_DIR:-/src/scans}
      - REPORT_DIR=${REPORT_DIR:-/src/reports}
      - OLLAMA_HOST=${OLLAMA_HOST:-ollama}
      - OLLAMA_PORT=${OLLAMA_PORT:-11434}
    #web-related variables
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - FLASK_SERVER=${BACKEND_SERVER}
      #-- Windows/Linux start
      - FLASK_PORT=${BACKEND_PORT:-5000}
      #-- windows/linux end

      #-- macOS start
      # - FLASK_PORT=${BACKEND_PORT:-5001}
      #-- macOS end
      - SECRET_KEY=${FLASK_SECRET_KEY}
    #Standalone-related Variables
      - SERVER_CNF=${SERVER_CNF}
      - AUTH_PORT=${AUTH_PORT}
      - AUTH_CRT=${AUTH_CRT}
      - AUTH_KEY=${AUTH_KEY}
      - AUTH_PASS=${AUTH_PASS}
      - AUTHED_PORT=${AUTHED_PORT}
      - AUTHED_CRT=${AUTHED_CRT}
      - AUTHED_KEY=${AUTHED_KEY}
      - AUTHED_PASS=${AUTHED_PASS}
    #Databse-related Variables
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}  
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    expose:
      #-- Windows/Linux start
      - ${BACKEND_PORT:-5000}
      #-- Windows/Linux end
      #-- macOS start
      # - ${BACKEND_PORT:-5001}
      #-- macOS end
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
      - ${AUTHED_PORT}:${AUTHED_PORT}
    command: ['']
    depends_on:
      ollama:
        condition: service_healthy
      database:
        condition: service_healthy
    networks:
      - backend
      - frontend
    healthcheck:
      test: curl --silent --fail http://${BACKEND_SERVER}:${BACKEND_PORT}/ || exit 1
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  backend-dev:
    container_name: cyberclinic-backend
    build:
      context: backend
      target: builder
      args:
        - BACKEND_SERVER=${BACKEND_SERVER:-backend-dev}
        - BACKEND_PORT=${BACKEND_PORT:-5000}
        - AUTHED_CRT=${AUTHED_CRT}
    environment:
      - SCAN_DIR=${SCAN_DIR:-/src/scans}
      - REPORT_DIR=${REPORT_DIR:-/src/reports}
      - OLLAMA_HOST=${OLLAMA_HOST:-ollama}
      - OLLAMA_PORT=${OLLAMA_PORT:-11434}
    #Web-related Variables
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - FLASK_SERVER=${BACKEND_SERVER}
      #-- Windows/Linux start
      - FLASK_PORT=${BACKEND_PORT:-5000}
      #-- Windows/Linux end
      #-- macOS start
      # - FLASK_PORT=${BACKEND_PORT:-5001}
      #-- macOS end
      - SECRET_KEY=${FLASK_SECRET_KEY}
    #Standalone-related Variables
      - SERVER_CNF=${SERVER_CNF}
      - AUTH_PORT=${AUTH_PORT}
      - AUTH_CRT=${AUTH_CRT}
      - AUTH_KEY=${AUTH_KEY}
      - AUTH_PASS=${AUTH_PASS}
      - AUTHED_PORT=${AUTHED_PORT}
      - AUTHED_CRT=${AUTHED_CRT}
      - AUTHED_KEY=${AUTHED_KEY}
      - AUTHED_PASS=${AUTHED_PASS}
    #Databse-related Variables
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}  
      - DB_PASS=${DB_PASS}
      - DB_HOST=database
      - DB_PORT=${DB_PORT}
    #sysreptor-related variables
      - REPTOR_SERVER_URL=http://${REPTOR_SERVER}:${REPTOR_PORT}
      - REPTOR_API_TOKEN=${REPTOR_API_TOKEN}
    volumes:
      - ./backend:/src
    #-- windows/linux start
    ports:
      #-- Windows/Linux start
      - ${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}
      #-- Windows/Linux end
      #-- macOS start
      # - ${BACKEND_PORT:-5001}:${BACKEND_PORT:-5001}
      #-- macOS end
      - ${AUTH_PORT}:${AUTH_PORT}
      - ${AUTHED_PORT}:${AUTHED_PORT}
    command: ['--debug']
    networks:
      - backend
      - frontend
    depends_on:
      ollama:
        condition: service_healthy
      database:
        condition: service_healthy

  ollama:
    container_name: cyberclinic-ollama
    build: 
      context: ollama
      dockerfile: Dockerfile
    environment:
      - OLLAMA_ORIGINS="http://${BACKEND_SERVER},https://${BACKEND_SERVER},http://localhost,https://localhost"
    expose:
      - ${OLLAMA_PORT:-11434}
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
       test: curl --silent --fail http://localhost:${OLLAMA_PORT:-11434}/ || exit 1
       interval: 30s
       timeout: 10s
       retries: 5
    

  database:
    container_name: cyberclinic-database
    image: bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      - POSTGRESQL_DATABASE=${DB_NAME}
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASS}
      - POSTGRESQL_PORT_NUMBER=${DB_PORT}
      - POSTGRESQL_MAX_CONNECTIONS=100
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    # Expose datbase locally for development and testing
    # Comment out the two lines below for production deployment
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    networks:
      - backend
    healthcheck:
      test: pg_isready -U $$DB_USER -d $$DB_NAME
      interval: 30s
      timeout: 30s
      start_period: 30s
      retries: 3

volumes:
  ollama_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

# Done By Austin Finch